scriptencoding utf-8
set encoding=utf-8

let $VIMDIR=expand("<sfile>:h")
source $VIMDIR/xdg.vim

" Plugins
packadd vim-jetpack
call jetpack#begin()
call jetpack#add('tani/vim-jetpack', {'opt': 1})
call jetpack#add('sheerun/vim-polyglot')
call jetpack#end()

" Appearance
syntax on
set title
set number
set ruler
set wrap
set showcmd
set showmatch
set scrolloff=10
set wildmenu
set laststatus=2
set statusline=%<%F\ %m%r%h%w%y%{'['.(&fenc!=''?&fenc:&enc).(&bomb?':BOM':'').']['.&ff.']'}%=%4v(0x%04.4B)\ %l/%L(%P)
set list
set listchars=tab:>-,extends:<,trail:- ",eol:<
highlight JpSpace cterm=underline ctermfg=Blue guifg=Blue
autocmd BufRead,BufNew * match JpSpace /＿/

" Encoding
set termencoding=utf-8
set fileencodings=utf-8,iso-2022-jp,cp932,euc-jp
set enc=utf-8
set ff=unix
autocmd BufNewFile,BufReadPost * set fileencoding=utf-8

" Indent
set tabstop=4
set autoindent
set expandtab
set smartindent
set shiftwidth=4
set softtabstop=4
set smarttab
set paste
nnoremap ,s :%s/<C-v><C-m>//<CR>
nnoremap ,,s :$s/\s*$//<CR>
nnoremap <leader>i1 :set softtabstop=1<CR>:set shiftwidth=1
nnoremap <leader>i2 :set softtabstop=2<CR>:set shiftwidth=2
nnoremap <leader>i4 :set softtabstop=4<CR>:set shiftwidth=4

" Completion
set wildmenu
set wildchar=<tab>
set wildmode=list:full
set history=1000
set complete+=k
set nrformats-=octal
set ignorecase
set smartcase
set wrapscan
set noincsearch
set hlsearch
cnoremap <C-p> <Up>
cnoremap <Up> <C-p>
cnoremap <C-n> <Down>
cnoremap <Down> <C-n>

" Backup
set nobackup
set noswapfile

source $VIMDIR/shared.vim

if filereadable(glob('~/.vimrc.local'))
  source ~/.vimrc.local
endif
